const SESSION_TTL_SECONDS = 86400; // 24 hours

const INTENTS = {
  APPOINTMENT_BOOKING: 'APPOINTMENT_BOOKING',
  DOCTOR_AVAILABILITY: 'DOCTOR_AVAILABILITY',
  REPORT_STATUS: 'REPORT_STATUS',
  KNOWLEDGE_QUERY: 'KNOWLEDGE_QUERY',
  HUMAN_ESCALATION: 'HUMAN_ESCALATION',
  UNKNOWN: 'UNKNOWN'
};

const WORKFLOWS = {
  APPOINTMENT_BOOKING: 'APPOINTMENT_BOOKING',
  DOCTOR_AVAILABILITY: 'DOCTOR_AVAILABILITY',
  REPORT_STATUS: 'REPORT_STATUS',
  KNOWLEDGE_QUERY: 'KNOWLEDGE_QUERY',
  HUMAN_ESCALATION: 'HUMAN_ESCALATION'
};

const FALLBACK_MESSAGE = "We could not process your request at the moment. Please try again or contact support.";

module.exports = {
  SESSION_TTL_SECONDS,
  INTENTS,
  WORKFLOWS,
  FALLBACK_MESSAGE
};
